name: Auto Checkin Job

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  auto-sign:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 手动缓存依赖
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # pip 默认缓存路径
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. 随机等待与任务执行（保持原有配置）
      - name: Generate random minute and wait
        id: random_wait
        run: |
          RANDOM_MINUTE=$((RANDOM % 60))
          CURRENT_MINUTE=$(date +%M)
          if [ "$CURRENT_MINUTE" -gt "$RANDOM_MINUTE" ]; then
            WAIT_SECONDS=$(( (60 - CURRENT_MINUTE + RANDOM_MINUTE) * 60 ))
          else
            WAIT_SECONDS=$(( (RANDOM_MINUTE - CURRENT_MINUTE) * 60 ))
          fi
          sleep $WAIT_SECONDS

      - name: Run auto checkin script
        id: run_script
        continue-on-error: true
        env:
          CONFIGS: ${{ secrets.CONFIGS }}
        run: |
          echo "任务执行时间：$(date)"
          python main.py
